version: 2

jobs:
  test:
    docker:
      - image: cimg/python:3.11.3

    environment:
      PYTHON_BIN: python3
      PYTHON_VERSION: 3.11

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}

      - run:
          name: Install test dependencies
          command: |
            ${PYTHON_BIN} -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -U setuptools
            # Install package with dependencies
            pip install .[test]

      - save_cache:
          paths:
            - ./venv
          key: v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}

      # run Flake8!
      - run:
          name: Flake8 Compliance
          command: |
            . venv/bin/activate
            ${PYTHON_BIN} setup.py flake8

      # run tests!
      - run:
          name: Unit-Tests
          command: |
            . venv/bin/activate
            ${PYTHON_BIN} setup.py nosetests


workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
